VERSION_YEAR = 2022
VERSION_MONTH = int('12')
VERSION_DAY = int('16')
VERSION_HOUR = int('12')
VERSION_MINUTE = int('08')
MAJOR_VERSION = 1
MINOR_VERSION = 8
PATCH_VERSION = 202212161208
version_date = '2022/12/16 12:08'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
