VERSION_YEAR = 2021
VERSION_MONTH = int('12')
VERSION_DAY = int('02')
VERSION_HOUR = int('13')
VERSION_MINUTE = int('11')
MAJOR_VERSION = 1
MINOR_VERSION = 1
PATCH_VERSION = 202112021311
version_date = '2021/12/02 13:11'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
