VERSION_YEAR = 2022
VERSION_MONTH = int('05')
VERSION_DAY = int('16')
VERSION_HOUR = int('10')
VERSION_MINUTE = int('16')
MAJOR_VERSION = 1
MINOR_VERSION = 3
PATCH_VERSION = 202205161016
version_date = '2022/05/16 10:16'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
